meta_product_name: "Oddz"
meta_title: "Oddz - Making the world a bettor place"
meta_description: "Bet on your favourite youtube celebrities on this revolutionary social betting platform"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@_oddz_"
